# Generated by Django 5.2.17 on 2026-09-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.TextField(max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('email', models.TextField(max_length=100)),
            ],
        ),
    ]
