# Generated by Django 5.2.17 on 2026-09-18 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaVeterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(blank=True, max_length=100)),
                ('tratamiento', models.CharField(blank=True, max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='Mascota.mascota')),
            ],
        ),
    ]
