# Generated by Django 5.2.17 on 2026-09-18 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.DeleteModel(
            name='Propietario',
        ),
    ]
